/*
Copyright isaaguilar.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/galleybytes/terraform-operator/pkg/apis/tf/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTerraforms implements TerraformInterface
type FakeTerraforms struct {
	Fake *FakeTfV1beta1
	ns   string
}

var terraformsResource = v1beta1.SchemeGroupVersion.WithResource("terraforms")

var terraformsKind = v1beta1.SchemeGroupVersion.WithKind("Terraform")

// Get takes name of the terraform, and returns the corresponding terraform object, and an error if there is any.
func (c *FakeTerraforms) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.Terraform, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(terraformsResource, c.ns, name), &v1beta1.Terraform{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Terraform), err
}

// List takes label and field selectors, and returns the list of Terraforms that match those selectors.
func (c *FakeTerraforms) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.TerraformList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(terraformsResource, terraformsKind, c.ns, opts), &v1beta1.TerraformList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.TerraformList{ListMeta: obj.(*v1beta1.TerraformList).ListMeta}
	for _, item := range obj.(*v1beta1.TerraformList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested terraforms.
func (c *FakeTerraforms) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(terraformsResource, c.ns, opts))

}

// Create takes the representation of a terraform and creates it.  Returns the server's representation of the terraform, and an error, if there is any.
func (c *FakeTerraforms) Create(ctx context.Context, terraform *v1beta1.Terraform, opts v1.CreateOptions) (result *v1beta1.Terraform, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(terraformsResource, c.ns, terraform), &v1beta1.Terraform{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Terraform), err
}

// Update takes the representation of a terraform and updates it. Returns the server's representation of the terraform, and an error, if there is any.
func (c *FakeTerraforms) Update(ctx context.Context, terraform *v1beta1.Terraform, opts v1.UpdateOptions) (result *v1beta1.Terraform, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(terraformsResource, c.ns, terraform), &v1beta1.Terraform{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Terraform), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTerraforms) UpdateStatus(ctx context.Context, terraform *v1beta1.Terraform, opts v1.UpdateOptions) (*v1beta1.Terraform, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(terraformsResource, "status", c.ns, terraform), &v1beta1.Terraform{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Terraform), err
}

// Delete takes name of the terraform and deletes it. Returns an error if one occurs.
func (c *FakeTerraforms) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(terraformsResource, c.ns, name, opts), &v1beta1.Terraform{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTerraforms) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(terraformsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.TerraformList{})
	return err
}

// Patch applies the patch and returns the patched terraform.
func (c *FakeTerraforms) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.Terraform, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(terraformsResource, c.ns, name, pt, data, subresources...), &v1beta1.Terraform{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Terraform), err
}
