apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terraform-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  - nodes
  verbs:
  - '*'

- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - '*'

- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'

- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - '*'

- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create

- apiGroups:
  - apps
  resourceNames:
  - terraform-operator
  resources:
  - deployments/finalizers
  verbs:
  - update

- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get

- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get

- apiGroups:
  - tf.galleybytes.com
  resources:
  - '*'
  verbs:
  - '*'

- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  resourceNames:
  - terraforms.tf.galleybytes.com
  verbs:
  - '*'
