apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraform-operator
  namespace: tf-system
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: terraform-operator
      component: controller
  template:
    metadata:
      labels:
        app: terraform-operator
        component: controller
    spec:
      serviceAccountName: terraform-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
      - name: terraform-operator
        image: "isaaguilar/terraform-operator:latest"
        imagePullPolicy: IfNotPresent
        command:
        - terraform-operator
        args:
        - --zap-log-level=debug
        - --zap-encoder=console
        - --disable-conversion-webhook
        env:
        - name: WATCH_NAMESPACE # Leave blank to watch all namespaces
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: OPERATOR_NAME
          value: terraform-operator
        resources:
          limits:
            cpu: 50m
            memory: 128M
          requests:
            cpu: 25m
            memory: 128M
