apiVersion: v1
kind: Service
metadata:
  name: terraform-operator-webhook
  namespace: tf-system
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app: terraform-operator
    release: terraform-operator
  sessionAffinity: None
  type: ClusterIP