apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terraform-operator-webhook
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update

- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list

- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  resourceNames:
  - terraforms.tf.isaaguilar.com
  verbs:
  - '*'