name: Build Terraform Operator Container Image

on: [push]

jobs:
  Terraform-Operator-AMD_x86_64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.20"

    - name: Log in to registry
      run: echo "${{ secrets.PKG_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Build and push amd64
      run: |
        make docker-build-local docker-push

  Terraform-Operator-ARM64:
    runs-on: [arm64]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.20"

    - name: Log in to registry
      run: echo "${{ secrets.PKG_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Build and push arm64
      run: |
        make docker-build-local-arm docker-push-arm

  Release-Terraform-Operator:
    runs-on: [pi]
    needs:
    - Terraform-Operator-AMD_x86_64
    - Terraform-Operator-ARM64
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Log in to registry
      run: echo "${{ secrets.PKG_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Build and push amd64
      run: |
          make docker-release