name: Run Build

on: [push]

jobs:
  amd64build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: Build and push amd64
      run: |
        make docker-build-local docker-push

  arm64build:
    runs-on: [arm64]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # The arm64 custom runner already has golang installed
    # - name: Set up Go
    #   uses: actions/setup-go@v2
    #   with:
    #     go-version: 1.19

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: Build and push arm64
      run: |
        make docker-build-local-arm docker-push-arm

  release:
    runs-on: [pi]
    needs:
    - amd64build
    - arm64build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: Build and push amd64
      run: |
          make docker-release